vich_uploader:
    db_driver: orm

    mappings:
        figures:
            uri_prefix: /images/figures
            upload_destination: '%kernel.project_dir%/public/images/figures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
